### ISSUE TITLE
feat: add pod IP as environment variable in simple-deployment chart

### ISSUE THREAD

**Issue by Kerwood** [ok-amba/default-ok-charts#51]
Add an env variable named `POD_IP` from fieldpath `status.podIP` on the deployment.
This pod IP is consumed by OTEL.

```
spec:
  ...
  template:
    ...
    spec:
      containers:
        - env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
```
